### ISSUE TITLE
Missing papers

### ISSUE THREAD

**Issue by dxlong2000** [Value4AI/Awesome-LLM-in-Social-Science#5]
Dear authors, 

Thank you for your great list. I would like to invite adding two papers:

- [Aligning Large Language Models with Human Opinions through Persona Selection and Value–Belief–Norm Reasoning](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=uZyF8wwAAAAJ&sortby=pubdate&citation_for_view=uZyF8wwAAAAJ:Se3iqnhoufwC)
- [Multi-expert Prompting Improves Reliability, Safety, and Usefulness of Large Language Models](https://scholar.google.com/citations?view_op=view_citation&hl=en&user=uZyF8wwAAAAJ&sortby=pubdate&citation_for_view=uZyF8wwAAAAJ:iH-uZ7U-co4C)

Thanks!

**Comment by henry-yeh** [comment]
Thank you for your awesome contributions!

Please feel free to open PR and insert the papers where you think they are most suitable.

**Comment by dxlong2000** [comment]
Sure thanks
